import { useRef,useState } from "react";
import { Bold, Italic, Underline, Code, List, Paperclip, Send, X } from "lucide-react";
import type { TicketStatus } from "@/entities/ticket/model/types";
import { answerTemplates,ticketStatuses,validateAttachments,type Constraint } from "@/entities/ticket/model/detail";
export type ComposeInput={text:string;internal:boolean;status:TicketStatus;constraint:string;units:number;files:File[]};
export function MessageComposer({internal=false,status,constraints,onSend,onNoAnswer}:{internal?:boolean;status:TicketStatus;constraints:Constraint[];onSend:(input:ComposeInput)=>string|null;onNoAnswer?:()=>void}){
 const [text,setText]=useState("");const [files,setFiles]=useState<File[]>([]);const [nextStatus,setStatus]=useState<TicketStatus|null>(null);const [constraint,setConstraint]=useState("");const [units,setUnits]=useState(0);const [error,setError]=useState("");const ref=useRef<HTMLTextAreaElement>(null);const fileInput=useRef<HTMLInputElement>(null);
 function format(before:string,after=before){const textarea=ref.current;if(!textarea)return;const start=textarea.selectionStart,end=textarea.selectionEnd;setText(text.slice(0,start)+before+text.slice(start,end)+after+text.slice(end));requestAnimationFrame(()=>{textarea.focus();textarea.setSelectionRange(start+before.length,end+before.length);});}
 function submit(event:React.FormEvent){event.preventDefault();const result=onSend({text,internal,status:nextStatus??status,constraint,units,files});if(result){setError(result);return;}setText("");setFiles([]);setUnits(0);setStatus(null);setError("");if(fileInput.current)fileInput.current.value="";}
 return <form className={`message-composer ${internal?"message-composer--internal":""}`} onSubmit={submit}>
 {!internal&&<div className="composer-tools">{[{label:"Жирный",icon:Bold,before:"**"},{label:"Курсив",icon:Italic,before:"*"},{label:"Подчёркнутый",icon:Underline,before:"__"},{label:"Код",icon:Code,before:"`"},{label:"Список",icon:List,before:"\n• ",after:""}].map(({label,icon:Icon,before,after})=><button type="button" key={label} aria-label={label} title={label} onClick={()=>format(before,after)}><Icon size={13}/></button>)}</div>}
 <textarea ref={ref} aria-label={internal?"Сообщение коллеге":"Ответ клиенту"} placeholder={internal?"Написать ответ коллеге":"Написать ответ"} value={text} onChange={event=>setText(event.target.value)} rows={internal?2:3}/>
 {!internal&&<div className="composer-options"><label>Поменять статус:<select value={nextStatus??status} onChange={event=>setStatus(event.target.value as TicketStatus)}>{ticketStatuses.map(value=><option key={value}>{value}</option>)}</select></label><label>Ограничение:<select value={constraint} onChange={event=>{setConstraint(event.target.value);setUnits(0);}}><option value="">Без списания</option>{constraints.map(c=><option key={c.name} value={c.name}>{c.name} ({c.used}/{c.limit})</option>)}</select></label><label><span className="sr-only">Количество</span><input type="number" min={0} step={1} disabled={!constraint} value={units} onChange={event=>setUnits(Number(event.target.value))}/></label><label>Шаблон:<select value="" onChange={event=>setText(answerTemplates[Number(event.target.value)]?.text??text)}><option value="">Выберите шаблон</option>{answerTemplates.map((template,index)=><option key={template.name} value={index}>{template.name}</option>)}</select></label></div>}
 {files.length>0&&<ul className="composer-files">{files.map((file,index)=><li key={`${file.name}-${index}`}>{file.name}<button type="button" aria-label={`Убрать ${file.name}`} onClick={()=>setFiles(files.filter((_,i)=>i!==index))}><X size={12}/></button></li>)}</ul>}
 {error&&<p role="alert" className="composer-error">{error}</p>}
 <div className="composer-buttons"><button className={internal?"danger-button":"primary-button"} type="submit"><Send size={13}/>Отправить</button><button className="secondary-button" type="button" onClick={()=>fileInput.current?.click()}><Paperclip size={13}/>Прикрепить файл</button>{onNoAnswer&&<button type="button" className="no-answer-button" onClick={onNoAnswer}>Не дозвонились</button>}</div>
 <input ref={fileInput} type="file" multiple hidden onChange={event=>{const selected=[...files,...Array.from(event.target.files??[])];const problem=validateAttachments(selected);if(problem)setError(problem);else{setFiles(selected);setError("");}event.target.value="";}}/>
 </form>;
}
