import { CheckCheck, Download, Pencil, Trash2, UserRound } from "lucide-react";
import type { Attachment, TicketMessage } from "@/entities/ticket/model/detail";
import type { TicketSession } from "@/shared/lib/access/ticket-access";
import { canEditTicketMessage, canDeleteTicketMessage } from "@/shared/lib/access/ticket-access";
import { MessageText } from "./message-text";
export function TicketConversation({messages,session,onDownload,onDelete,onEdit}:{session:TicketSession;messages:TicketMessage[];onDownload:(file:Attachment)=>void;onDelete:(id:string)=>void;onEdit:(id:string)=>void}){
 return <div className="ticket-conversation" role="log" aria-label="Переписка по заявке">{messages.map((message,index)=>{
  const day=message.createdAt.slice(0,10);const showDay=day!==messages[index-1]?.createdAt.slice(0,10);
  return <div key={message.id}>{showDay&&<div className="conversation-date"><span>{new Date(message.createdAt).toLocaleDateString("ru-RU",{timeZone:"UTC",day:"numeric",month:"long",year:"numeric"})}</span></div>}{message.kind==="event"?<div className="conversation-event"><span>{message.text}</span>{canDeleteTicketMessage(session,message)&&<button className="event-delete" aria-label="Удалить запись истории" onClick={()=>onDelete(message.id)}><Trash2 size={12}/></button>}</div>:<article className={`conversation-message conversation-message--${message.kind}`}><div className="conversation-author"><span className="conversation-avatar"><UserRound size={19}/></span><div><strong>{message.author}</strong><small>{new Date(message.createdAt).toLocaleString("ru-RU",{timeZone:"UTC",dateStyle:"short",timeStyle:"short"})}{message.kind==="internal"&&" · Только сотрудникам"}</small></div>{(canEditTicketMessage(session,message)||canDeleteTicketMessage(session,message))&&<div className="conversation-actions">{canEditTicketMessage(session,message)&&<button title="Редактировать сообщение" aria-label="Редактировать сообщение" onClick={()=>onEdit(message.id)}><Pencil size={12}/></button>}{canDeleteTicketMessage(session,message)&&<button title="Удалить сообщение" aria-label="Удалить сообщение" onClick={()=>onDelete(message.id)}><Trash2 size={12}/></button>}</div>}</div><div className="conversation-bubble"><MessageText text={message.text}/>{message.attachments.length>0&&<div className="message-attachments">{message.attachments.map(file=><button key={file.id} onClick={()=>onDownload(file)}><Download size={13}/>{file.name}<small>{Math.ceil(file.size/1024)} КБ</small></button>)}</div>}{message.kind!=="client"&&<CheckCheck className="message-read" size={12} aria-label="Демонстрационная отметка доставки"/>}</div></article>}</div>;
 })}</div>;
}
