version: '3.4'

services:
  migrator:
    image: cr.yandex/crp3htsb576q3sp0eub8/kv.server.migrator:dev
    build:
      context: .
      dockerfile: src/KV.Server.DbMigrator/Dockerfile
      args:
        GITLAB_NPM_TOKEN: ${GITLAB_NPM_TOKEN}
  int:
    image: cr.yandex/crp3htsb576q3sp0eub8/kv.server.int:dev
    build:
      context: .
      dockerfile: src/KV.Server.Web/Dockerfile
      args:
        GITLAB_NPM_TOKEN: ${GITLAB_NPM_TOKEN}
  ext:
    image: cr.yandex/crp3htsb576q3sp0eub8/kv.server.ext:dev
    build:
      context: .
      dockerfile: src/KV.Server.PublicWeb/Dockerfile
      args:
        GITLAB_NPM_TOKEN: ${GITLAB_NPM_TOKEN}
